import 'dart:convert';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

part 'local_database.g.dart'; // Generated by drift_dev

// ── Tables ────────────────────────────────────────────────────

class LocalAnswers extends Table {
  TextColumn get id => text()();
  TextColumn get sessionId => text()();
  TextColumn get questionId => text()();
  TextColumn get answerText => text().nullable()();
  DateTimeColumn get answeredAt => dateTime()();
  BoolColumn get synced => boolean().withDefault(const Constant(false))();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}

class LocalExams extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  IntColumn get durationMinutes => integer()();
  TextColumn get questionsJson => text()(); // JSON encoded list
  DateTimeColumn get fetchedAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}

// ── Database ──────────────────────────────────────────────────

@DriftDatabase(tables: [LocalAnswers, LocalExams])
class LocalDatabase extends _$LocalDatabase {
  LocalDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // ── Answers ─────────────────────────────────────────────────
  Future<void> saveAnswer({
    required String sessionId,
    required String questionId,
    required String answerText,
  }) async {
    final id = '${sessionId}_$questionId';
    await into(localAnswers).insertOnConflictUpdate(
      LocalAnswersCompanion.insert(
        id: id,
        sessionId: sessionId,
        questionId: questionId,
        answerText: Value(answerText),
        answeredAt: DateTime.now(),
        synced: const Value(false),
      ),
    );
  }

  Future<List<LocalAnswer>> getPendingAnswers(String sessionId) {
    return (select(localAnswers)
          ..where((t) => t.sessionId.equals(sessionId) & t.synced.equals(false)))
        .get();
  }

  Future<void> markSynced(String id) async {
    await (update(localAnswers)
          ..where((t) => t.id.equals(id)))
        .write(const LocalAnswersCompanion(synced: Value(true)));
  }

  // ── Exams (Offline Cache) ───────────────────────────────────
  Future<void> cacheExam({
    required String id,
    required String title,
    required int durationMinutes,
    required List<Map<String, dynamic>> questions,
  }) async {
    await into(localExams).insertOnConflictUpdate(
      LocalExamsCompanion.insert(
        id: id,
        title: title,
        durationMinutes: durationMinutes,
        questionsJson: jsonEncode(questions),
        fetchedAt: Value(DateTime.now()),
      ),
    );
  }

  Future<LocalExam?> getCachedExam(String id) {
    return (select(localExams)..where((t) => t.id.equals(id))).getSingleOrNull();
  }
}

// ── Connection ────────────────────────────────────────────────

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    return driftDatabase(
      name: 'secure_cbt_offline',
    );
  });
}

// ── DAO Provider ──────────────────────────────────────────────
// Will be set up via Riverpod in the DI layer
