org.gradle.jvmargs=-Xmx3072M -XX:MaxMetaspaceSize=1024M -XX:ReservedCodeCacheSize=256M -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
